cask_args appdir: "/Applications"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
tap "homebrew/core"

brew "anyenv"
brew "asciidoc"
brew "fish"
brew "fontconfig"
brew "ghq"
brew "git"
brew "git-lfs"
brew "hub"
brew "jq"
brew "neovim"
brew "peco"
brew "tig"
brew "tmux"
brew "tree"

cask "appcleaner"
cask "authy"
cask "clipy"
cask "docker"
cask "drawio"
cask "font-hack-nerd-font"
cask "google-chrome"
cask "google-japanese-ime"
cask "karabiner-elements"
cask "iterm2"
cask "notion"
cask "postman"
cask "slack"
cask "visual-studio-code"
cask "zoom"
