#!/bin/bash

set -eu

logging() {
  if [ "$#" -eq 0 -o "$#" -gt 1 ]; then
    echo "Usage: <msg>"
    return 1
  fi

  local text="$1"
  printf "[$(date +%H:%M:%S)] $text"
}

is_exists() {
  which "$1" >/dev/null 2>&1
  return $?
}

lower() {
  if [ $# -eq 0 ]; then
    cat <&0
  elif [ $# -eq 1 ]; then
    if [ -f "$1" -a -r "$1" ]; then
      cat "$1"
    else
      echo "$1"
    fi
  else
    return 1
  fi | tr "[:upper:]" "[:lower:]"
}

ostype() {
  # shellcheck disable=SC2119
  uname | lower
}

os_detect() {
  export PLATFORM
  case "$(ostype)" in
  *'linux'*) PLATFORM='linux' ;;
  *'darwin'*) PLATFORM='osx' ;;
  *) PLATFORM='unknown' ;;
  esac
}

install_build_tool() {
  os_detect
  # makeが存在しないと後続が続かない
  if [ "$PLATFORM" == 'linux' ]; then
    if ! is_exists "make"; then
      echo y | sudo apt update
      echo y | sudo apt upgrade
      sudo apt install -y build-essential curl file git
    fi
  fi
}

install_brew() {
  os_detect
  if [ "$PLATFORM" == 'linux' ]; then
  
    if [ ! -e ./.bash_profile ]; then
      touch ./.bash_profile
    fi
    
    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
    test -d ~/.linuxbrew && eval $(~/.linuxbrew/bin/brew shellenv)
    test -d /home/linuxbrew/.linuxbrew && eval $(/home/linuxbrew/.linuxbrew/bin/brew shellenv)
    test -r ~/.bash_profile && echo "eval \$($(brew --prefix)/bin/brew shellenv)" >>~/.bash_profile
    echo "eval \$($(brew --prefix)/bin/brew shellenv)" >>~/.profile
    
    # fish
    echo 'eval (/home/linuxbrew/.linuxbrew/bin/brew shellenv)' >> ~/.config/fish/env.fish
  elif [ "$PLATFORM" == 'osx' ]; then
    /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
    # fish
    echo 'eval (/opt/homebrew/bin/brew shellenv)' >> ~/.config/fish/env.fis
  else
    exit 1
  fi

}

# ==============================

GITHUB_URL=https://github.com/knsugiyama/dotfiles.git
DOTPATH=~/.dotfiles
export DOTPATH

download() {
  logging "install: start download..."

  os_detect
  if [ "$PLATFORM" == 'linux' ]; then
    if ! is_exists "git"; then
      sudo apt install -y git
    fi
  fi

  git clone --recursive "$GITHUB_URL" "$DOTPATH"

  install_build_tool
  install_brew
}

deploy() {
  logging "install: start deploy..."
  if [ ! -d $DOTPATH ]; then
    exit 1
  fi
  cd "$DOTPATH"

  make skipfiles
  make deploy
}

initialize() {
  logging "install: start initialize..."
  local path install_shell

  os_detect
  if [ "$PLATFORM" == 'linux' ]; then
    path=${DOTPATH}/etc/init/linux
  elif [ "$PLATFORM" == 'osx' ]; then
    path=${DOTPATH}/etc/init/mac
  else
    exit 1
  fi

  cat ${path}/installation-order | while read install_shell; do
    if [ line != '' ]; then
      logging "shell name: ${path}/${install_shell}"
      bash "${path}/${install_shell}"
      . ~/.bash_profile
    fi
  done

  if [ "$PLATFORM" == 'linux' ]; then
    echo `which fish` | sudo tee -a /etc/shells
  elif [ "$PLATFORM == 'osx' ]; then
    sudo sh -c "echo '/opt/homebrew/bin/fish' >> /etc/shells"
  fi
  chsh -s $(which fish)
  
}

install() {
  download &&
    deploy &&
    initialize
}

install

exec $SHELL -l
