#!/bin/bash

. ${DOTPATH}/etc/scripts/lib/logging.sh
. ${DOTPATH}/etc/scripts/lib/os_detect.sh

OS=$(os_detect)

echo $(log_echo "start update.")
echo $(log_info "###### update git. ######")
if [ ! -d ".git" ]; then
  git init
  git remote add origin https://github.com/knsugiyama/dotfiles.git
  git fetch origin
  git checkout -b master
else
  git checkout master
  git pull
fi

echo $(log_info "###### packages update. ######")
if [ ${OS} == 'osx' ]; then
  brew upgrade
  brew upgrade --cask
elif [ ${OS} == 'linux' ]; then
  sudo apt -y update
  sudo apt -y upgrade
  sudo apt autoremove
fi

echo $(log_info "###### anyenv update. ######")
anyenv update
