[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = "ulwlu/elly.vim"
hook_add = """
set termguicolors
colorscheme elly
"""

[[plugins]]
repo = "hoob3rt/lualine.nvim"
hook_source = """
source ~/.config/nvim/plugins/lua/lualine.rc.lua
"""

[[plugins]]
repo = 'kyazdani42/nvim-web-devicons'
hook_source = """
source ~/.config/nvim/plugins/lua/nvim-web-devicons.rc.lua
"""

[[plugins]]
repo = 'Shougo/context_filetype.vim'

[[plugins]]
repo = 'luochen1990/rainbow'
hook_add = '''
let g:rainbow_active = 1
'''

[[plugins]]
repo ="kristijanhusak/defx-git"

[[plugins]]
repo ="kristijanhusak/defx-icons"

[[plugins]]
repo = 'Shougo/defx.nvim'
depends = ['defx-git', 'defx-icons']
hook_add = """
source ~/.config/nvim/plugins/vim/defx.rc.vim
"""

[[plugins]]
repo = 'roxma/nvim-yarp'

[[plugins]]
repo = 'roxma/vim-hug-neovim-rpc'

[[plugins]]
repo = 'jiangmiao/auto-pairs'

[[plugins]]
repo = 'neovim/nvim-lspconfig'
hook_add = """
source ~/.config/nvim/plugins/lua/lspconfig.rc.lua
"""

[[plugins]]
repo = 'nvim-treesitter/nvim-treesitter'
hook_post_update = """
'TSUpdate'
source ~/.config/nvim/plugins/lua/nvim-treesitter.rc.vim
"""

[[plugins]]
repo = 'nvim-lua/completion-nvim'
hook_add = """
source ~/.config/nvim/plugins/vim/completion-nvim.rc.vim
"""

# [[plugins]]
# repo = 'glepnir/lspsaga.nvim'
# hook_add = """
# source ~/.config/nvim/plugins/lua/lspsaga.rc.lua
# """

[[plugins]]
repo = 'folke/lsp-colors.nvim'
hook_add = """
source ~/.config/nvim/plugins/lua/lsp-colors.rc.lua
"""

[[plugins]]
repo = 'nvim-lua/popup.nvim'

[[plugins]]
repo = 'nvim-lua/plenary.nvim'

[[plugins]]
repo = 'nvim-telescope/telescope.nvim'
hook_add = """
source ~/.config/nvim/plugins/lua/telescope.rc.lua
"""
