[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = "cocopon/iceberg.vim"
hook_add = """
source ~/.config/nvim/plugins/iceberg.vim
"""

[[plugins]] # Status Line
repo = "itchyny/lightline.vim"
hook_add = """
source ~/.config/nvim/plugins/lightline.vim
"""

[[plugins]] # インデントを見やすくする
repo = 'Yggdroot/indentLine'

[[plugins]] # Cheatsheet
repo = "reireias/vim-cheatsheet"
hook_add = """
source ~/.config/nvim/plugins/vim-cheatsheet.vim
"""

# ------------------------------------
# Dark powered plugins
# ------------------------------------
[[plugins]]
repo ="kristijanhusak/defx-git"
hook_add = """
source ~/.config/nvim/plugins/defx-git.vim
"""

[[plugins]] # ファイルエクスプローラー
repo = 'Shougo/defx.nvim'
depends = ['defx-git']
hook_add = """
source ~/.config/nvim/plugins/defx.vim
"""

[[plugins]] # Neovimのインターフェースを統合
repo = "Shougo/denite.nvim"
hook_add = """
source ~/.config/nvim/plugins/denite.vim
"""

[[plugins]] # Neovim上でターミナルを実行
repo = "shougo/deol.nvim"
hook_add = """
source ~/.config/nvim/plugins/deol.vim
"""

