[[plugins]]
repo = "cocopon/iceberg.vim"
hook_add = """
source ~/.config/nvim/plugins/iceberg.vim
"""

[[plugins]] # アイコン
repo = 'ryanoasis/vim-devicons'

[[plugins]] # 非同期処理
repo = 'Shougo/vimproc.vim'

[[plugins]] # インデントを見やすくする
repo = 'Yggdroot/indentLine'

[[plugins]] # カーソル位置のコンテキストに合わせてftを切り替える
repo = 'osyo-manga/vim-precious'
depends = ['context_filetype.vim']

[[plugins]] # カーソル位置のコンテキストのftを判定するライブラリ
repo = 'Shougo/context_filetype.vim'

[[plugins]] # Status Line
repo = "itchyny/lightline.vim"
hook_add = """
source ~/.config/nvim/plugins/lightline.vim
"""

[[plugins]] # LSP(Language Server Protocol)を使えるようにする
repo = "neoclide/coc.nvim"
rev = "release"
merged = '0'
hook_add = """
source ~/.config/nvim/plugins/coc.vim
"""

# ------------------------------------
# Markdown
# ------------------------------------
[[plugins]]
repo = "plasticboy/vim-markdown"

[[plugins]]
repo = "iamcco/markdown-preview.nvim"
on_ft = ['markdown', 'pandoc.markdown', 'rmd']
build = 'sh -c "cd app & yarn install"'
hook_add = """
source ~/.config/nvim/plugins/markdown-preview.vim
"""

# ------------------------------------
# Dark powered plugins
# ------------------------------------
[[plugins]]
repo ="kristijanhusak/defx-git"
hook_add = """
source ~/.config/nvim/plugins/defx-git.vim
"""

[[plugins]]
repo ="kristijanhusak/defx-icons"

[[plugins]] # ファイルエクスプローラー
repo = 'Shougo/defx.nvim'
depends = ['defx-git', 'defx-icons']
hook_add = """
source ~/.config/nvim/plugins/defx.vim
"""

[[plugins]] # Neovimのインターフェースを統合
repo = "Shougo/denite.nvim"
hook_add = """
source ~/.config/nvim/plugins/denite.vim
"""

[[plugins]] # Neovim上でターミナルを実行
repo = "shougo/deol.nvim"
hook_add = """
source ~/.config/nvim/plugins/deol.vim
"""
