[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/context_filetype.vim'

[[plugins]]
repo = "cocopon/iceberg.vim"
hook_add = """
source ~/.config/nvim/plugins/iceberg.rc.vim
"""

[[plugins]]
repo = "itchyny/lightline.vim"
hook_add = """
source ~/.config/nvim/plugins/lightline.rc.vim
"""

[[plugins]]
repo = "reireias/vim-cheatsheet"
hook_add = """
source ~/.config/nvim/plugins/vim-cheatsheet.rc.vim
"""

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'airblade/vim-gitgutter'

[[plugins]]
repo = 'luochen1990/rainbow'
hook_add = '''
let g:rainbow_active = 1
'''

[[plugins]]
repo ="kristijanhusak/defx-git"

[[plugins]]
repo = 'Shougo/defx.nvim'
depends = ['defx-git']
hook_add = """
source ~/.config/nvim/plugins/defx.rc.vim
"""

[[plugins]]
repo = 'Shougo/denite.nvim'
hook_add = """
source ~/.config/nvim/plugins/denite.rc.vim
"""

[[plugins]]
repo = 'jlanzarotta/bufexplorer'

[[plugins]]
repo = 'jiangmiao/auto-pairs'

[[plugins]]
repo = "neoclide/coc.nvim"
merged = 0
rev = "release"
hook_add = """
source ~/.config/nvim/plugins/coc.rc.vim
"""
