[[plugins]]
repo = "plasticboy/vim-markdown"
on_ft = ['markdown', 'pandoc.markdown', 'rmd']
hook_add = '''
source ~/.config/nvim/plugins/vim-markdown.rc.vim
'''

[[plugins]]
repo = "iamcco/markdown-preview.nvim"
on_ft = ['markdown', 'pandoc.markdown', 'rmd']
build = 'sh -c "cd app && yarn install"'
hook_add = '''
source ~/.config/nvim/plugins/markdown-preview.rc.vim
'''

[[plugins]] 
repo  = 'cespare/vim-toml'
on_ft = ['toml']

[[plugins]]
repo = 'dag/vim-fish'
on_ft = ['fish']

[[plugins]]
repo = 'pangloss/vim-javascript'
on_ft = ['javascript', 'javascript.jsx', 'typescript']

[[plugins]]
repo = 'leafgarland/typescript-vim'
on_ft = ['javascript', 'javascript.jsx', 'typescript']

[[plugins]]
repo = 'maxmellon/vim-jsx-pretty'
on_ft = ['javascript', 'javascript.jsx', 'typescript']
