[[plugins]] # 閉じタグを自動で補完
repo = 'alvan/vim-closetag'
on_ft = ['html', 'xhtml', 'javascript', 'typescript', 'javascript.jsx', 'typescript.tsx']
hook_add = '''
source ~/.config/nvim/plugins/vim-closetag.rc.vim
'''

[[plugins]]
repo = "plasticboy/vim-markdown"
on_ft = ['markdown', 'pandoc.markdown', 'rmd']
hook_add = '''
source ~/.config/nvim/plugins/vim-markdown.rc.vim
'''

[[plugins]]
repo = "iamcco/markdown-preview.nvim"
on_ft = ['markdown', 'pandoc.markdown', 'rmd']
build = 'sh -c "cd app && yarn install"'
hook_add = '''
source ~/.config/nvim/plugins/markdown-preview.rc.vim
'''

[[plugins]] 
repo  = 'cespare/vim-toml'
on_ft = ['toml']

[[plugins]]
repo = 'dag/vim-fish'
on_ft = ['fish']
