# ------------------------------------
# Markdown
# ------------------------------------
[[plugins]]
repo = "plasticboy/vim-markdown"

[[plugins]]
repo = "iamcco/markdown-preview.nvim"
on_ft = ['markdown', 'pandoc.markdown', 'rmd']
build = 'sh -c "cd app & yarn install"'
hook_add = '''
source ~/.config/nvim/plugins/markdown-preview.vim
'''

[[plugins]] # git操作
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'airblade/vim-gitgutter'

[[plugins]] # カラフル括弧
repo = 'luochen1990/rainbow'
hook_add = '''
let g:rainbow_active = 1
'''

[[plugins]] # 閉じタグを自動で補完
repo = 'alvan/vim-closetag'
on_ft = ['html', 'xhtml', 'javascript', 'typescript', 'javascript.jsx', 'typescript.tsx']
hook_add = '''
source ~/.config/nvim/plugins/vim-closetag.vim
'''

[[plugins]]
repo = "thinca/vim-quickrun"
hook_add = '''
source ~/.config/nvim/plugins/vim-quickrun.vim
'''

# ------------------------------------
# LSP
# ------------------------------------
[[plugins]]
repo = 'neoclide/coc.nvim'
rev = 'release'
build = '''
git checkout release
'''
hook_add = '''
source ~/.config/nvim/plugins/coc.vim
'''
