cask_args appdir: "/Applications"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-versions"
tap "homebrew/core"

brew "git"
brew "git-lfs"
brew "peco"
brew "ghq"
brew "jq"
brew "tig"
brew "fish"
brew "fzf"
brew "fontconfig"
brew "anyenv"

cask "google-chrome"
cask "google-japanese-ime"
cask "authy"
cask "iterm2"
cask "visual-studio-code"
cask "docker"
cask "postman"
cask "slack"
cask "font-cica"
cask "adoptopenjdk8"
cask "karabiner-elements"
cask "clipy"

brew "gradle"
brew "maven"
