cask_args appdir: "/Applications"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-versions"
tap "homebrew/core"

brew "anyenv"
brew "fontconfig"
brew "fish"
brew "ghq"
brew "git"
brew "git-lfs"
brew "hub"
brew "jq"
brew "peco"
brew "tig"

cask "appcleaner"
cask "adoptopenjdk8"
cask "authy"
cask "clickup"
cask "clipy"
cask "docker"
cask "google-chrome"
cask "google-japanese-ime"
cask "karabiner-elements"
cask "iterm2"
cask "postman"
cask "slack"
cask "visual-studio-code"

brew "gradle"
brew "maven"
