#!/usr/bin/env bash

set -eu

. ${DOTPATH}/etc/scripts/lib/os_detect.sh

OS=$(os_detect)

if [ ${OS} == 'osx' ]; then
  echo "set PATH $(brew --prefix)/opt/grep/libexec/gnubin \$PATH" >> ~/.config/fish/env.fish
fi
