#cloud-config
hostname: myvm # この仮想環境のホスト名を "myvm" に設定
locale: en_US.UTF-8 # システムロケールを英語(us)に設定
timezone: Asia/Tokyo # システム時刻を日本時間に設定 UTC+9:00
ssh_pwauth: no # パスワード認証による ssh ログインを禁止
package_update: true # パッケージインストール前にパッケージリポジトリを更新
package_upgrade: true # パッケージインストール前に既存パッケージを更新
package_reboot_if_required: true # 再起動が必要なパッケージがある場合に再起動を実施

# apt パッケージをインストール
packages:
  - sshfs # ssh 接続でディレクトリマウントするためのパッケージ
  - curl
  - ca-certificates # 基本的なCA認証を取得するパッケージ
  - neovim
  - jq # json ファイルのパーサー
  - tree # ディレクトリやファイルをツリー表示するコマンド
  - git # ソースコードのバージョン管理
  - zstd # zstandard 形式の圧縮コマンド
  - avahi-daemon # ローカル環境のホスト名解決
  - build-essential
  - unzip
  - ripgrep
  - libffi-dev
  - libgmp-dev
  - libncurses-dev
  - libfuse-dev
  - pkg-config
  - libssl-dev
  - cmake
  - gnupg
  - gcc

# ユーザー作成
users:
  - name: myvm # 新規作成するユーザー名の設定
    lock_passwd: true # パスワードによるログインを禁止
    sudo: ALL=(ALL) NOPASSWD:ALL # sudo 実行の際にパスワード入力を不要化
    shell: /bin/bash # デフォルトで使用する shell を設定
    ssh-authorized-keys: # ssh 接続時に使用する、公開鍵を設定
      - <YOUR SSH PUBLIC KEY> # ~/.ssh/multipass/myvm/myvm.pub を記載
    groups: # docker コマンド実施の際に sudo を不要にするため docker グループへ追加
      - docker

# コマンド実行（すべての初期化処理の最後に実行）
runcmd:
  # マウント先のディレクトリを "myvm" ユーザーの権限で作成
  - su -c "mkdir /home/myvm/sync_myvm" - myvm
  # Docker インストール (公式リポジトリ利用)
  - apt update
  - install -m 0755 -d /etc/apt/keyrings
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg
  - chmod a+r /etc/apt/keyrings/docker.gpg
  - echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu $(. /etc/os-release && echo "$VERSION_CODENAME") stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null
  - apt update
  - apt install -y docker-ce docker-ce-cli containerd.io
  # act インストール
  - curl --proto '=https' --tlsv1.2 -sSf https://raw.githubusercontent.com/nektos/act/master/install.sh | bash -s -- -b /usr/local/bin v0.2.60
