# https://alacritty.org/config-alacritty.html
[general]
import = [
    "~/.config/alacritty/themes/catppuccin-macchiato.toml"
]

# immediately reloadwhen this file is updated
live_config_reload = true

[terminal.shell]
program = "/bin/zsh" 
args = ["-l", "-c", "tmux attach -t main || tmux new -s main"]

[window]
# window size
dimensions = { columns = 200, lines = 60 }
dynamic_padding = true
padding = { x = 4, y = 4 }
opacity = 0.95

[cursor]
style = "Beam"

[font]
size = 12
offset = { x = 0, y = 2 }

# font names by type
normal = { family = "Moralerspace Argon NF", style = "Regular" }
bold = { family = "Moralerspace Argon NF", style = "Bold" }
italic = { family = "Moralerspace Argon NF", style = "Italic" }
bold_italic = { family = "Moralerspace Argon NF", style = "Bold Italic" }

[selection]
semantic_escape_chars = "`~!@#$%^&*()-=+[{]}\\|;:'\",.<>/?｀～！＠＃＄％＾＆＊（）－＝＋［｛］｝＼｜；：＇＂，．＜＞／？「」、。【】『』　てにをはがのともへでや"
save_to_clipboard = true

[scrolling]
history = 10000
multiplier = 3
